services:
  - type: web
    name: d2p
    runtime: static
    staticPublishPath: standalone_site
    pullRequestPreviewsEnabled: false
  - type: web
    name: d2p-live-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn live_feed_proxy:app --bind 0.0.0.0:$PORT --workers 2
    pullRequestPreviewsEnabled: false
